### ISSUE TITLE
Installation instructions

### ISSUE THREAD

**Issue by ghost** [petusa/CordovaServer#6]
I followed your limited instructions and got the liver-server to run without issue, but I am seeing no results when navigating to localhost:8080.

Should I `npm install corodova-server` in the root of my cordova project? 
After installation would I run `node node_modules/corodva-sever` ?

Here's my current file structure:
├── foo
│   ├── config.xml
│   ├── hooks
│   │   └── README.md
│   ├── platforms
│   ├── plugins
│   └── www
│       ├── css
│       │   └── index.css
│       ├── img
│       │   └── logo.png
│       ├── index.html
│       └── js
│           └── index.js
├── node_modules
│   └── cordova-server
│       ├── cordova-server.js
│       ├── index.js
│       ├── index.js.orig
│       ├── injected-cordova.js
│       ├── injected-cordova_plugins.js
│       ├── injected-cordova_plugins.js.orig
│       ├── node_modules
│       ├── npm-publish.sh
│       ├── package.json
│       ├── package.json.orig
│       ├── README.md
│       ├── scripts
│       │   └── generate_cordova.js
│       └── www
│           └── cordova.js

**Comment by petusa** [comment]
Hello @joe-singer, 

Try to install cordova-server globally with the -g flag:   npm install -g cordova. So that it puts the cordova-server command to the global path and you can simply run it from (anywhere) but most likely from your cordova project's root folder (where the config.xml is located).

Hope this helps.

Best,
Peter
